controller_list:
  - name: fake_right_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
  - name: fake_left_controller
    type: $(arg fake_execution_type)
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint_finger_1
      - right_joint_finger_2
      - right_joint_finger_3
  - name: fake_left_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_joint_finger_1
      - left_joint_finger_2
      - left_joint_finger_3
initial:  # Define initial robot poses per group
  - group: right
    pose: Right Vertical
  - group: left
    pose: Left Vertical