controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
  - name: right_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - right_joint_finger_1
      - right_joint_finger_2
      - right_joint_finger_3
  - name: left_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - left_joint_finger_1
      - left_joint_finger_2
      - left_joint_finger_3